//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TruncateGCode.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TruncateGCode.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Generated by Something Version 0.05)
        ///
        ///G21 G90 G40
        ///
        ///(pocket 1)
        ///G0 Z2
        ///T0 M6
        ///G17
        ///M3
        ///G0 X75.2205 Y31.1552
        ///G1 Z-1 F350
        ///G3 X75.118 Y30.682000000000002 I1.048 J-0.474 F350
        ///G3 X76.268 Y29.531999999999996 I1.1500000000000001 J0
        ///G1 X81.67500000000001 Y29.531999999999996
        ///G3 X82.825 Y30.682000000000002 I0 J1.1500000000000001
        ///G3 X82.72500000000001 Y31.151 I-1.1500000000000001 J0
        ///G1 X80.037 Y37.166000000000004
        ///G3 X77.94 Y37.17 I-1.05 J-0.469
        ///G1 X75.22 Y31.155
        ///G0 Z2
        ///G0 X87.0564 Y24.9716
        ///G1 Z-1 F350
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParseCodeTestFile1 {
            get {
                return ResourceManager.GetString("ParseCodeTestFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Generated by Something Version 0.05)
        ///
        ///G21 G90 G40
        ///
        ///(pocket 1)
        ///G0 Z2
        ///T0 M6
        ///G17
        ///M3
        ///G0 X75.2205 Y31.1552
        ///G1 Z-1 F350
        ///G3 X75.118 Y30.682000000000002 I1.048 J-0.474 F350
        ///G3 X76.268 Y29.531999999999996 I1.1500000000000001 J0
        ///G1 X81.67500000000001 Y29.531999999999996
        ///G3 X82.825 Y30.682000000000002 I0 J1.1500000000000001
        ///G3 X82.72500000000001 Y31.151 I-1.1500000000000001 J0
        ///G1 X80.037 Y37.166000000000004
        ///G3 X77.94 Y37.17 I-1.05 J-0.469
        ///G1 X75.22 Y31.155
        ///G0 Z2
        ///G0 X87.0564 Y24.9716
        ///G1 Z-1 F350
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ParseCodeTestFile1ExpectedResult {
            get {
                return ResourceManager.GetString("ParseCodeTestFile1ExpectedResult", resourceCulture);
            }
        }
    }
}
